version: '3.7'

services:
  yandex2mqtt:
    build: ./
    container_name: yandex2mqtt
    restart: always
    init: true
    volumes:
      - ./config.js:/opt/yandex2mqtt/config.js
      - ./db-storage:/opt/yandex2mqtt/db-storage
    ports:
      - "4433:4433"
    environment:
      - MQTT_USER
      - MQTT_PASS
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.yandex2mqtt.rule=Host(`y2m.office.ziondev.ru`)"
      - "traefik.http.routers.yandex2mqtt.service=yandex2mqtt-service"

      - "traefik.http.routers.yandex2mqtt-tls.rule=Host(`y2m.office.ziondev.ru`)"
      - "traefik.http.routers.yandex2mqtt-tls.tls=true"
      - "traefik.http.routers.yandex2mqtt-tls.tls.certresolver=default"
      - "traefik.http.routers.yandex2mqtt-tls.service=yandex2mqtt-service"

      - "traefik.http.services.yandex2mqtt-service.loadbalancer.server.port=4433"
